services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile.n8n-custom
    container_name: n8n-local-custom
    ports:
      - "5678:5678"
    environment:
      - TZ=America/Sao_Paulo
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_CUSTOM_EXTENSIONS=/opt/n8n-custom
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
